// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChyU_kq-1hR7Km-PLeMC278PWQvKMXcMM',
    appId: '1:453558371032:web:903844d222e87889a10dad',
    messagingSenderId: '453558371032',
    projectId: 'medicine-reminder-1802e',
    authDomain: 'medicine-reminder-1802e.firebaseapp.com',
    storageBucket: 'medicine-reminder-1802e.firebasestorage.app',
    measurementId: 'G-T794PWDCMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVhjkWGFq0kBqlPk0UVypn7XmliwFShc',
    appId: '1:453558371032:android:563948ed13343f9ba10dad',
    messagingSenderId: '453558371032',
    projectId: 'medicine-reminder-1802e',
    storageBucket: 'medicine-reminder-1802e.firebasestorage.app',
  );
}

